[[docs]]
  name = "ff_team"
  weight = 10
  identifier = "ff_team"
  url = "/docs/ff_team/general_information/order-page-ff/"

#[[docs]]
 # name = "Help"
 # weight = 60
 # identifier = "help"
 # url = "/docs/help/"

[[main]]
  name = "Docs"
  url = "/docs/ff_team/general_information/order-page-ff/"
  weight = 10

# [[main]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 20



# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
